### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ian-whitestone** [ian-whitestone/pyspark-vs-dask#5]
## `r5.xlarge`: Running out of disk space despite having a 50GB EBS volume & 36GB RAM with `cnt = cnt.compute(num_workers=10)`

- the two dataframes being joined together are from a 20 GB & 10GB avro dataset in S3

```python
(dask) ubuntu@XXXXX:~/pyspark-vs-dask/scripts/test2$ python dsk_multi_df_filter_cnt.py
2018-10-21 03:08:22,523|INFO|logger: START: Creating dask bag 1
2018-10-21 03:09:26,090|INFO|logger: FINISH: Dask bag1 created
2018-10-21 03:09:26,090|INFO|logger: START: Creating dask dataframe 1
2018-10-21 03:09:51,815|INFO|logger: FINISH: Dask dataframe 1 created
2018-10-21 03:09:51,815|INFO|logger: START: Creating dask bag 2
2018-10-21 03:10:56,966|INFO|logger: FINISH: Dask bag2 created
2018-10-21 03:10:56,966|INFO|logger: START: Creating dask dataframe 2
2018-10-21 03:11:17,154|INFO|logger: FINISH: Dask dataframe 2 created
2018-10-21 03:11:17,154|INFO|logger: START: Joining dataframes
2018-10-21 03:11:29,696|INFO|logger: FINISH: Finished joining dataframes
2018-10-21 03:11:29,696|INFO|logger: START: Starting count
Traceback (most recent call last):
  File "dsk_multi_df_filter_cnt.py", line 89, in <module>
    cnt = cnt.compute(num_workers=10)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/base.py", line 395, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/local.py", line 501, in get_async
    raise_exception(exc, tb)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/local.py", line 272, in execute_task
    result = _execute_task(task, data)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/local.py", line 253, in _execute_task
    return func(*args2)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/dask/dataframe/shuffle.py", line 479, in shuffle_group_3
    p.append(d, fsync=True)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/partd/encode.py", line 25, in append
    self.partd.append(data, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/partd/buffer.py", line 45, in append
    self.flush(keys)
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/partd/buffer.py", line 99, in flush
    self.slow.append(dict(zip(keys, self.fast.get(keys))))
  File "/home/ubuntu/miniconda3/envs/dask/lib/python3.6/site-packages/partd/file.py", line 46, in append
    os.fsync(f)
OSError: [Errno 28] No space left on device
```

Seems like i still have disk space available....where is writing files to?
![screen shot 2018-10-22 at 8 52 02 am](https://user-images.githubusercontent.com/11096727/47293314-caafbd80-d5d7-11e8-9631-01ccb0f65201.png)

Maybe it cleans up files after...here is another test running on a c5.9xlarge with 100GB EBS volume, this was taken mid-test:

```
Filesystem      Size  Used Avail Use% Mounted on
udev             35G     0   35G   0% /dev
tmpfs           6.9G  289M  6.6G   5% /run
/dev/nvme0n1p1   97G   52G   46G  54% /
tmpfs            35G     0   35G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            35G     0   35G   0% /sys/fs/cgroup
none             35G     0   35G   0% /run/shm
/dev/loop0       88M   88M     0 100% /snap/core/5328
tmpfs           6.9G     0  6.9G   0% /run/user/1000
```

https://github.com/dask/dask/issues/1659

Cleaning up files after force-killed job: `rm -rf /tmp/tmpw4uytluo.partd`

**Comment by ian-whitestone** [comment]
## Changing number of workers doesn't seem to have an effect

Running this [test](https://github.com/ian-whitestone/pyspark-vs-dask/blob/master/scripts/test4/dsk_filter_cnt.py) on a c4.8xlarge with 36 cores and 60GB ram...

```
67 (s) 1.12 (min): Creating dask bag with filter
0 (s) 0.01 (min): Creating dask dataframe
451 (s) 7.53 (min): Starting count
520 (s) 8.67 (min): Total time for test: dsk_filter_cnt_threading_36
81 (s) 1.36 (min): Creating dask bag with filter
0 (s) 0.01 (min): Creating dask dataframe
454 (s) 7.57 (min): Starting count
536 (s) 8.94 (min): Total time for test: dsk_filter_cnt_threading_25
75 (s) 1.26 (min): Creating dask bag with filter
0 (s) 0.02 (min): Creating dask dataframe
448 (s) 7.48 (min): Starting count
524 (s) 8.75 (min): Total time for test: dsk_filter_cnt_threading_15
87 (s) 1.45 (min): Creating dask bag with filter
1 (s) 0.02 (min): Creating dask dataframe
417 (s) 6.96 (min): Starting count
506 (s) 8.43 (min): Total time for test: dsk_filter_cnt_threading_5
```

When trying multiprocessing with 36 workers, don't see more than 1 python process running during compute step.

**Comment by ian-whitestone** [comment]
## Dask distributed memory consumption

Coming soon..

**Comment by ian-whitestone** [comment]
https://stackoverflow.com/questions/268680/how-can-i-monitor-the-thread-count-of-a-process-on-linux

`ps huH p 11852 | wc -l`

`sudo apt install htop`

**Comment by ian-whitestone** [comment]
## Questions for Martin

- Is dask.bag --> dask dataframe recommended? or should i look to use intake --> dask?
- Under what scenarios would you want to use multiprocessing with dask.dataframes? how bout joining?
- threaded/multiprocessing vs dask-distributed??
